DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
  ID VARCHAR (100) PRIMARY KEY,
  NAME VARCHAR (100) NOT NULL
 ),
 
INSERT INTO EMPLOYEE (ID, NAME) VALUES ('123', 'Employee_1');
INSERT INTO EMPLOYEE (ID, NAME) VALUES ('123', 'Employee_2');
INSERT INTO EMPLOYEE (ID, NAME) VALUES ('123', 'Employee_3')
