apiVersion: v1
kind: PersistentVolume
metadta:
  name: mysql-pv-volume
  labels: 
    type: local
    
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: ". /vol"
