apiVersion: v1
kind: PersistentVolumeClaim
metadta:
  name: mysql-pv-claim
  labels: 
    type: local
    
spec:
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
